import * as date from './components/date'
import * as slider from './components/slider'
import * as weather from './components/weather'
import * as quotes from './components/quotes'
import * as player from './components/player'
